# Generated by Django 4.1.3 on 2022-11-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arduino',
            name='ruta',
        ),
    ]
